# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
team=sqlite3.connect("dreamteam.db")
from playerlist1 import Ak_otherwindow
from points1 import Bk_otherwindow



class Ui_MainWindow(object):

    def openWindow(self):
        self.otherwindow = QtWidgets.QMainWindow()
        self.ui = Ak_otherwindow()
        self.ui.setupUi(self.otherwindow)
        self.otherwindow.show()
    def openWindow2(self):
        self.otherwindow = QtWidgets.QMainWindow()
        self.ui = Bk_otherwindow()
        self.ui.setupUi(self.otherwindow)
        self.otherwindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1188, 737)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setAutoFillBackground(False)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAccessibleDescription("")
        self.centralwidget.setAutoFillBackground(False)
        
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(550, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_4.setText("")
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAutoFillBackground(False)
        self.label_21.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_21.setText("")
        self.label_21.setScaledContents(False)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAutoFillBackground(False)
        self.label_23.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_23.setText("")
        self.label_23.setScaledContents(True)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_22.setText("")
        self.label_22.setScaledContents(True)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_24.setText("")
        self.label_24.setScaledContents(True)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_3.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAutoFillBackground(False)
        self.label_25.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_25.setText("")
        self.label_25.setScaledContents(True)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_3.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAutoFillBackground(False)
        self.label_26.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_26.setText("")
        self.label_26.setScaledContents(True)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_3.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAutoFillBackground(False)
        self.label_27.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.label_27.setText("")
        self.label_27.setScaledContents(True)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_3.addWidget(self.label_27)
        spacerItem5 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setAutoFillBackground(True)
        self.pushButton_3.setStyleSheet("color: rgb(160, 160, 160);")
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setChecked(False)
        self.pushButton_3.setAutoDefault(True)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(True)
        self.pushButton_2.setStyleSheet("color: rgb(160, 160, 160);")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setAutoFillBackground(True)
        self.pushButton_4.setStyleSheet("color: rgb(160, 160, 160);")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(True)
        self.pushButton.setStyleSheet("color: rgb(160, 160, 160);")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.H = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.H.setFont(font)
        self.H.setText("")
        self.H.setObjectName("H")
        self.verticalLayout_2.addWidget(self.H)
        spacerItem7 = QtWidgets.QSpacerItem(17, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem7)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_22 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_22.setMaximumSize(QtCore.QSize(18, 16777215))
        self.radioButton_22.setText("")
        self.radioButton_22.setAutoExclusive(False)
        self.radioButton_22.setObjectName("radioButton_22")
        self.gridLayout_3.addWidget(self.radioButton_22, 11, 14, 1, 1)
        self.radioButton_23 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_23.setMaximumSize(QtCore.QSize(18, 16777215))
        self.radioButton_23.setText("")
        self.radioButton_23.setAutoExclusive(False)
        self.radioButton_23.setObjectName("radioButton_23")
        self.gridLayout_3.addWidget(self.radioButton_23, 12, 14, 1, 1)
        self.R2 = QtWidgets.QLabel(self.centralwidget)
        self.R2.setText("")
        self.R2.setObjectName("R2")
        self.gridLayout_3.addWidget(self.R2, 7, 5, 1, 1)
        self.V5 = QtWidgets.QLabel(self.centralwidget)
        self.V5.setText("")
        self.V5.setObjectName("V5")
        self.gridLayout_3.addWidget(self.V5, 12, 6, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.radioButton_2.setText("")
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_3.addWidget(self.radioButton_2, 6, 12, 1, 1)
        self.V2 = QtWidgets.QLabel(self.centralwidget)
        self.V2.setText("")
        self.V2.setObjectName("V2")
        self.gridLayout_3.addWidget(self.V2, 7, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 6, 1, 1)
        self.E5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.E5.setFont(font)
        self.E5.setText("")
        self.E5.setObjectName("E5")
        self.gridLayout_3.addWidget(self.E5, 12, 2, 1, 1)
        self.E3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.E3.setFont(font)
        self.E3.setText("")
        self.E3.setObjectName("E3")
        self.gridLayout_3.addWidget(self.E3, 10, 2, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_16.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_16.setText("")
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout_3.addWidget(self.radioButton_16, 11, 12, 1, 1)
        self.radioButton_20 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_20.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_20.setText("")
        self.radioButton_20.setAutoExclusive(False)
        self.radioButton_20.setObjectName("radioButton_20")
        self.gridLayout_3.addWidget(self.radioButton_20, 7, 14, 1, 1)
        self.L1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.L1.setFont(font)
        self.L1.setText("")
        self.L1.setObjectName("L1")
        self.gridLayout_3.addWidget(self.L1, 6, 3, 1, 2)
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_9.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_9.setFont(font)
        self.radioButton_9.setText("")
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_3.addWidget(self.radioButton_9, 12, 7, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 7, 16, 1, 1)
        self.R4 = QtWidgets.QLabel(self.centralwidget)
        self.R4.setText("")
        self.R4.setObjectName("R4")
        self.gridLayout_3.addWidget(self.R4, 11, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 3, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setMaximumSize(QtCore.QSize(16, 16777215))
        self.radioButton.setText("")
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_3.addWidget(self.radioButton, 6, 8, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 14, 2, 1, 1)
        self.L5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.L5.setFont(font)
        self.L5.setText("")
        self.L5.setObjectName("L5")
        self.gridLayout_3.addWidget(self.L5, 12, 3, 1, 2)
        self.radioButton_15 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_15.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_15.setText("")
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout_3.addWidget(self.radioButton_15, 10, 12, 1, 1)
        self.R3 = QtWidgets.QLabel(self.centralwidget)
        self.R3.setText("")
        self.R3.setObjectName("R3")
        self.gridLayout_3.addWidget(self.R3, 10, 5, 1, 1)
        self.L2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.L2.setFont(font)
        self.L2.setText("")
        self.L2.setObjectName("L2")
        self.gridLayout_3.addWidget(self.L2, 7, 3, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 14, 16, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_3.setText("")
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_3.addWidget(self.radioButton_3, 7, 8, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_17.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_17.setText("")
        self.radioButton_17.setAutoExclusive(False)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout_3.addWidget(self.radioButton_17, 12, 12, 1, 1)
        self.E1 = QtWidgets.QLabel(self.centralwidget)
        self.E1.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.E1.setFont(font)
        self.E1.setText("")
        self.E1.setScaledContents(False)
        self.E1.setObjectName("E1")
        self.gridLayout_3.addWidget(self.E1, 6, 2, 1, 1)
        self.V3 = QtWidgets.QLabel(self.centralwidget)
        self.V3.setText("")
        self.V3.setObjectName("V3")
        self.gridLayout_3.addWidget(self.V3, 10, 6, 1, 1)
        self.E4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.E4.setFont(font)
        self.E4.setText("")
        self.E4.setObjectName("E4")
        self.gridLayout_3.addWidget(self.E4, 11, 2, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_5.setText("")
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_3.addWidget(self.radioButton_5, 11, 8, 1, 1)
        self.R1 = QtWidgets.QLabel(self.centralwidget)
        self.R1.setText("")
        self.R1.setObjectName("R1")
        self.gridLayout_3.addWidget(self.R1, 6, 5, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 6, 16, 1, 1)
        self.radioButton_19 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_19.setMaximumSize(QtCore.QSize(16, 16777215))
        self.radioButton_19.setText("")
        self.radioButton_19.setAutoExclusive(False)
        self.radioButton_19.setObjectName("radioButton_19")
        self.gridLayout_3.addWidget(self.radioButton_19, 6, 14, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 7, 1, 1)
        self.E2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.E2.setFont(font)
        self.E2.setText("")
        self.E2.setObjectName("E2")
        self.gridLayout_3.addWidget(self.E2, 7, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 12, 16, 1, 1)
        self.radioButton_11 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_11.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_11.setFont(font)
        self.radioButton_11.setText("")
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName("radioButton_11")
        self.gridLayout_3.addWidget(self.radioButton_11, 7, 7, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 10, 16, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 5, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_6.setText("")
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_3.addWidget(self.radioButton_6, 12, 8, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_14.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_14.setText("")
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName("radioButton_14")
        self.gridLayout_3.addWidget(self.radioButton_14, 7, 12, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(150, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 6, 15, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setText("")
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_3.addWidget(self.radioButton_8, 11, 7, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem14, 11, 16, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setMaximumSize(QtCore.QSize(16, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setText("")
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_3.addWidget(self.radioButton_7, 6, 7, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_10.setMaximumSize(QtCore.QSize(17, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_10.setFont(font)
        self.radioButton_10.setText("")
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_3.addWidget(self.radioButton_10, 10, 7, 1, 1)
        self.R5 = QtWidgets.QLabel(self.centralwidget)
        self.R5.setText("")
        self.R5.setObjectName("R5")
        self.gridLayout_3.addWidget(self.R5, 12, 5, 1, 1)
        self.L3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.L3.setFont(font)
        self.L3.setText("")
        self.L3.setObjectName("L3")
        self.gridLayout_3.addWidget(self.L3, 10, 3, 1, 2)
        self.L4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setBold(True)
        font.setWeight(75)
        self.L4.setFont(font)
        self.L4.setText("")
        self.L4.setObjectName("L4")
        self.gridLayout_3.addWidget(self.L4, 11, 3, 1, 2)
        self.V1 = QtWidgets.QLabel(self.centralwidget)
        self.V1.setText("")
        self.V1.setObjectName("V1")
        self.gridLayout_3.addWidget(self.V1, 6, 6, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setMaximumSize(QtCore.QSize(17, 16777215))
        self.radioButton_4.setText("")
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_3.addWidget(self.radioButton_4, 10, 8, 1, 1)
        self.V4 = QtWidgets.QLabel(self.centralwidget)
        self.V4.setText("")
        self.V4.setObjectName("V4")
        self.gridLayout_3.addWidget(self.V4, 11, 6, 1, 1)
        self.radioButton_21 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_21.setMaximumSize(QtCore.QSize(18, 16777215))
        self.radioButton_21.setText("")
        self.radioButton_21.setAutoExclusive(False)
        self.radioButton_21.setObjectName("radioButton_21")
        self.gridLayout_3.addWidget(self.radioButton_21, 10, 14, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1188, 26))
        self.menubar.setObjectName("menubar")
        self.menuManage_Team = QtWidgets.QMenu(self.menubar)
        self.menuManage_Team.setTearOffEnabled(False)
        self.menuManage_Team.setSeparatorsCollapsible(False)
        self.menuManage_Team.setToolTipsVisible(False)
        self.menuManage_Team.setObjectName("menuManage_Team")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setCheckable(False)
        self.actionNEW_Team.setEnabled(True)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        self.menuManage_Team.addAction(self.actionNEW_Team)
        self.menuManage_Team.addSeparator()
        self.menuManage_Team.addAction(self.actionOPEN_Team)
        self.menuManage_Team.addSeparator()
        self.menuManage_Team.addAction(self.actionEVALUATE_Team)
        self.menubar.addAction(self.menuManage_Team.menuAction())
        self.menuManage_Team.triggered[QtWidgets.QAction].connect(self.menufunction)
        self.l=[self.L1,self.L2,self.L3,self.L4,self.L5]
        self.r=[self.R1,self.R2,self.R3,self.R4,self.R5]
        self.Rwk=[self.radioButton_7,self.radioButton_11,self.radioButton_10,self.radioButton_8,self.radioButton_9]
        for i in self.Rwk[:len(self.Rwk)]:
            i.setHidden(True)
        self.Rbat=[self.radioButton,self.radioButton_3,self.radioButton_4,self.radioButton_5,self.radioButton_6 ]
        for i in self.Rbat[:len(self.Rbat)]:
            i.setHidden(True)
        self.Rbwl=[self.radioButton_2,self.radioButton_14,self.radioButton_15,self.radioButton_16,self.radioButton_17]
        for i in self.Rbwl[:len(self.Rbwl)]:
            i.setHidden(True)
        self.Rar=[self.radioButton_19,self.radioButton_20,self.radioButton_21,self.radioButton_22,self.radioButton_23]
        for i in self.Rar[:len(self.Rar)]:
            i.setHidden(True)

        self.v=[self.V1,self.V2,self.V3,self.V4,self.V5]
        self.e=[self.E1,self.E2,self.E3,self.E4,self.E5]
        self.S=[self.label,self.label_2,self.label_3,self.label_4,self.label_21,self.label_23,self.label_22,self.label_24,self.label_25,self.label_26,self.label_27]
        
        
        self.radioButton_7.clicked.connect(lambda:self.save(self.radioButton_7,0,"WK"))
        self.radioButton_11.clicked.connect(lambda:self.save(self.radioButton_11,1,"WK"))
        
        self.radioButton.clicked.connect(lambda:self.save(self.radioButton,0,"BAT"))
        self.radioButton_3.clicked.connect(lambda:self.save(self.radioButton_3,1,"BAT"))
        self.radioButton_4.clicked.connect(lambda:self.save(self.radioButton_4,2,"BAT"))
        self.radioButton_5.clicked.connect(lambda:self.save(self.radioButton_5,3,"BAT"))
        self.radioButton_6.clicked.connect(lambda:self.save(self.radioButton_6,4,"BAT"))
       
        self.radioButton_2.clicked.connect(lambda:self.save(self.radioButton_2,0,"BWL"))
        self.radioButton_14.clicked.connect(lambda:self.save(self.radioButton_14,1,"BWL"))
        self.radioButton_15.clicked.connect(lambda:self.save(self.radioButton_15,2,"BWL"))
        self.radioButton_16.clicked.connect(lambda:self.save(self.radioButton_16,3,"BWL"))
        
        self.radioButton_19.clicked.connect(lambda:self.save(self.radioButton_19,0,"AR"))
        self.radioButton_20.clicked.connect(lambda:self.save(self.radioButton_20,1,"AR"))
        self.radioButton_21.clicked.connect(lambda:self.save(self.radioButton_21,2,"AR"))
        self.radioButton_22.clicked.connect(lambda:self.save(self.radioButton_22,3,"AR"))
        

        
            
       
        
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def menufunction(self,action):
        txt=(action.text())
        
        if txt=="NEW Team":
         
            text, ok = QtWidgets.QInputDialog.getText(MainWindow, 'Dream Team Selector', 'Enter name of team:')
            if ok and len(text.strip())!=0:
                self.name=str(text)
                self.pushButton_5.setEnabled(True)
                self.player=[]
                self.WK=[]
                self.BAT=[]
                self.BWL=[]
                self.AR=[]
                self.value=1000
                for i in self.Rwk[:len(self.Rwk)]:
                    i.setHidden(True)
                for i in self.Rbat[:len(self.Rbat)]:
                    i.setHidden(True)
                for i in self.Rbwl[:len(self.Rbwl)]:
                    i.setHidden(True)
                for i in self.Rar[:len(self.Rar)]:
                    i.setHidden(True)
                for i in self.r[:len(self.r)]:
                    i.setText("")
                for i in self.v[:len(self.v)]:
                    i.setText("")
                for i in self.e[:len(self.e)]:
                    i.setPixmap(QtGui.QPixmap(""))
                for y in self.l[:len(self.l)]:
                    y.setText("")  
                for i in self.S:
                    i.setStyleSheet("background-color: rgb(240, 240, 240);")
                    i.setText("")
                self.label_28.setText("0")
                self.label_9.setText(str(self.value))
                self.pushButton_5.setEnabled(True)
                self.H.setText("")

                self.pushButton_3.setText("WK(0)")
                self.pushButton_2.setText("BAT(0)")
                self.pushButton_4.setText("BWL(0)")
                self.pushButton.setText("AR(0)")
     
                self.pushButton_3.clicked.connect(lambda:self.show("WK"))
                self.pushButton_2.clicked.connect(lambda:self.show("BAT"))
                self.pushButton_4.clicked.connect(lambda:self.show("BWL"))
                self.pushButton.clicked.connect(lambda:self.show("AR"))
                self.pushButton_5.clicked.connect(lambda:self.savet())
            elif ok and len(text.strip())==0:
                self.showdlg("PLEASE ENTER VALID TEXT")

        if txt=="OPEN Team":
            self.openWindow()

        if txt=="EVALUATE Team":
            self.openWindow2()

        
            

    def show(self,n):
        ctg=n       
        for i in self.Rwk[:len(self.Rwk)]:
            i.setHidden(True)
        self.Rbat=[self.radioButton,self.radioButton_3,self.radioButton_4,self.radioButton_5,self.radioButton_6 ]
        for i in self.Rbat[:len(self.Rbat)]:
            i.setHidden(True)
        self.Rbwl=[self.radioButton_2,self.radioButton_14,self.radioButton_15,self.radioButton_16,self.radioButton_17]
        for i in self.Rbwl[:len(self.Rbwl)]:
            i.setHidden(True)
        self.Rar=[self.radioButton_19,self.radioButton_20,self.radioButton_21,self.radioButton_22,self.radioButton_23]
        for i in self.Rar[:len(self.Rar)]:
            i.setHidden(True)
        if ctg=="WK":
            self.H.setText("SELECT 1 WICKET KEEPER")
        elif ctg=="BAT":
            self.H.setText("SELECT 3-5 BATSMAN")
        elif ctg=="BWL":
            self.H.setText("SELECT 3-5 BOWLER")
        else:
            self.H.setText("SELECT 3-5 ALL ROUNDER")
        cur=team.cursor()
        sql="SELECT player,value FROM stats WHERE ctg='"+str(ctg)+"';"
        cur.execute(sql)
        self.result=cur.fetchall()
        self.a=len(self.result)
        
        for i in range(1):
            for y in self.l[:self.a]:
                self.result1=(self.result[i])
                y.setText(str(self.result1[0]))
                i=i+1
        for i in range(1):
            for k in self.v[:self.a]:
                self.result1=(self.result[i])
                k.setText(str(self.result1[1]))
                i=i+1   
        if ctg=="WK":
            self.E1.setPixmap(QtGui.QPixmap("WK\msd.png"))
            self.E1.setScaledContents(True)
            self.E2.setPixmap(QtGui.QPixmap("WK\dk.jpg"))
            self.E2.setScaledContents(True)
        elif ctg=="BAT":
            self.E1.setPixmap(QtGui.QPixmap("batsman\kohli.png"))
            self.E1.setScaledContents(True)
            self.E2.setPixmap(QtGui.QPixmap("batsman\dhawan.png"))
            self.E2.setScaledContents(True)
            self.E3.setPixmap(QtGui.QPixmap("batsman\\rohit.png"))
            self.E3.setScaledContents(True)
            self.E4.setPixmap(QtGui.QPixmap("batsman\\rahane.jpg"))
            self.E4.setScaledContents(True)
            self.E5.setPixmap(QtGui.QPixmap("batsman\yuvraj.jpg"))
            self.E5.setScaledContents(True)
        elif ctg=="BWL":
            self.E1.setPixmap(QtGui.QPixmap("BWL\\bhuvi.jpg"))
            self.E1.setScaledContents(True)
            self.E2.setPixmap(QtGui.QPixmap("BWL\\umesh.jpg"))
            self.E2.setScaledContents(True)
            self.E3.setPixmap(QtGui.QPixmap("BWL\\bumrah.jpg"))
            self.E3.setScaledContents(True)
            self.E4.setPixmap(QtGui.QPixmap("BWL\\ashwin.jpg"))
            self.E4.setScaledContents(True)
        else :
            self.E1.setPixmap(QtGui.QPixmap("AR\kedar.jpg"))
            self.E1.setScaledContents(True)
            self.E2.setPixmap(QtGui.QPixmap("AR\jadeja.jpg"))
            self.E2.setScaledContents(True)
            self.E3.setPixmap(QtGui.QPixmap("AR\hardik.jpg"))
            self.E3.setScaledContents(True)
            self.E4.setPixmap(QtGui.QPixmap("AR\\axar.jpg"))
            self.E4.setScaledContents(True)
                              
        for i in self.r[:self.a]:
            i.setText(ctg)
        for i in self.v[self.a:]:
            i.setText("")
        for i in self.r[self.a:]:
            i.setText("")
        if ctg=="WK":
            for i in self.Rwk[:self.a]:
                i.setHidden(False)
            for i in self.e[self.a:]:
                i.setPixmap(QtGui.QPixmap(""))
        elif ctg=="BAT":
            for i in self.Rbat[:self.a]:
                i.setHidden(False)
            for i in self.e[self.a:]:
                i.setPixmap(QtGui.QPixmap(""))
        elif ctg=="BWL":
            for i in self.Rbwl[:self.a]:
                i.setHidden(False)
            for i in self.e[self.a:]:
                i.setPixmap(QtGui.QPixmap(""))
        else :
            for i in self.Rar[:self.a]:
                i.setHidden(False)
            for i in self.e[self.a:]:
                i.setPixmap(QtGui.QPixmap(""))
        for y in self.l[self.a:]:
            y.setText("")
        

        
    def save(self,y,n,m):    
        if y.isChecked()==True:
                        
            self.result1=(self.result[n])
            a=str(self.result1[0])
            b=str(self.result1[1])
            self.value=self.value-int(b)
            self.label_9.setText(str(self.value))
            self.player.append(a)
            
            
            if len(self.player)>11 and self.value<0 :
                y.setChecked(False)
                m="11 PLAYER HAVE BEEN SELECTED AND NO POINTS LEFT "
                self.showdlg(m)
            elif self.value<0:
                y.setChecked(False)
                m="NOT ENOUGH POINTS TO SELECT THIS PLAYER"
                self.showdlg(m)
            if m=="WK":
                self.WK.append(a)
                self.pushButton_3.setText("WK("+str(len(self.WK))+")")  
                if len(self.WK)>1:
                    y.setChecked(False)
                    ms="SELECT ONLY 1 WICKET KEEPER"
                    self.showdlg(ms)
            elif m=="BAT":
                self.BAT.append(a)
                self.pushButton_2.setText("BAT("+str(len(self.BAT))+")")  
                if len(self.BAT)>5:
                    y.setChecked(False)
                    ms="SELECT 3-5 BATSMAN"
                    self.showdlg(ms)
            elif m=="BWL":
                self.BWL.append(a)
                self.pushButton_4.setText("BWL("+str(len(self.BWL))+")") 
                if len(self.BWL)>5:
                    y.setChecked(False)
                    ms="SELECT 3-5 BOWLER"
                    self.showdlg(ms) 
            elif m=="AR":
                self.AR.append(a)
                self.pushButton.setText("AR("+str(len(self.AR))+")")  
                if len(self.AR)>3:
                    y.setChecked(False)
                    ms="SELECT 3 ALL ROUNDER"
                    self.showdlg(ms) 
            for i in self.S[:len(self.player)]:
                i.setStyleSheet("background-color: rgb(0, 255, 0);") 
            if len(self.player)<12:
                self.S[len(self.player)-1].setText(str(len(self.player)))  
             
            self.label_28.setText(str(len(self.player)))
         
        if y.isChecked()==False:
            self.result1=(self.result[n])
            a=str(self.result1[0])
            b=str(self.result1[1])
            self.value=self.value+int(b)
            self.label_9.setText(str(self.value))
            self.player.remove(a) 
            if m=="WK":
                self.WK.remove(a)
                self.pushButton_3.setText("WK("+str(len(self.WK))+")")  
                
            elif m=="BAT":
                self.BAT.remove(a)
                self.pushButton_2.setText("BAT("+str(len(self.BAT))+")")  
            
            elif m=="BWL":
                self.BWL.remove(a)
                self.pushButton_4.setText("BWL("+str(len(self.BWL))+")") 
            elif m=="AR":
                self.AR.remove(a)
                self.pushButton.setText("AR("+str(len(self.AR))+")")  
                
            self.label_28.setText(str(len(self.player)))
            if len(self.player)<11:
                self.S[len(self.player)].setText("")
                self.S[len(self.player)].setStyleSheet("background-color: rgb(240, 240, 240);")
            

    def savet(self):
        
        if len(self.player)<11:
            m="SELECT "+str(11-len(self.player))+" MORE PLAYER TO COMPLETE YOUR TEAM!"
            self.showdlg(m)
            self.pushButton_5.setEnabled(True)
            return
        string=''
        for i in range(len(self.player)):
            string=string+str(self.player[i])
            if i<len(self.player)-1:
                string=string+","
        print(self.value)
        self.pushButton_5.setEnabled(False)
        cur=team.cursor()
        sql="INSERT INTO teams(name,players,value) VALUES ('"+self.name+"','"+string+"','"+str(1000-self.value)+"');"
        try:
            cur.execute(sql)
            team.commit()
            m="TEAM ADDED SUCCESSFULLY"
            self.showdlg(m)
        except:
            team.rollback()
            m="ERROR IN OPERATION" 
            self.showdlg(m)
        
        
            

    def showdlg(self, msg):
        Dialog = QtWidgets.QMessageBox()
        Dialog.setText(msg)
        Dialog.setWindowTitle("Dream Team Selector")
        ret=Dialog.exec()          

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "/11"))
        self.label_5.setText(_translate("MainWindow", "Payers"))
        self.label_9.setText(_translate("MainWindow", "1000"))
        self.label_8.setText(_translate("MainWindow", "Points Left"))
        self.label_28.setText(_translate("MainWindow", "0"))
        self.pushButton_3.setText(_translate("MainWindow", "WK(0)"))
        self.pushButton_2.setText(_translate("MainWindow", "BAT(0)"))
        self.pushButton_4.setText(_translate("MainWindow", "BWl(0)"))
        self.pushButton.setText(_translate("MainWindow", "AR(0)"))
        self.label_14.setText(_translate("MainWindow", "VALUE"))
        self.label_11.setText(_translate("MainWindow", "PLAYER NAME"))
        self.label_15.setText(_translate("MainWindow", "ROLE"))
        self.pushButton_5.setText(_translate("MainWindow", "SAVE TEAM"))
        self.menuManage_Team.setTitle(_translate("MainWindow", "Manage Team"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "OPEN Team"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
